apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  namespace: my-nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30225
  selector:
      app: nginx
