apiVersion: v1
kind: Service
metadata:
  name: nginx4
  labels:
    app: nginx4
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
      app: nginx4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx4
spec:
  selector:
    matchLabels:
      app: nginx4
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx4
    spec:
      containers:
      - name: nginx4
        image: nginx:1.21.5
        ports:
        - containerPort: 80
